INSERT INTO game_config (key, value, description) VALUES
  ('STEAL_WINDOW_SECONDS', '60', 'Seconds after RIPE before stealing opens'),
  ('STEAL_POOL_PERCENT', '0.40', 'Fraction of yield locked as steal pool'),
  ('STRANGER_DAILY_STEAL_LIMIT', '3', 'Max steals from strangers per day'),
  ('STEAL_COST_NORMAL', '15', NULL),
  ('STEAL_COST_BRONZE', '30', NULL),
  ('STEAL_COST_SILVER', '60', NULL),
  ('STEAL_COST_GOLD', '120', NULL),
  ('STEAL_COST_DIAMOND', '300', NULL),
  ('STEAL_COST_LEGENDARY', '1000', NULL),
  ('STEAL_UNITS_MIN', '1', NULL),
  ('STEAL_UNITS_MAX', '2', NULL),
  ('NEW_PLAYER_PROTECTION_LEVEL', '5', NULL),
  ('GRADE_NORMAL_RATE', '0.58', NULL),
  ('GRADE_BRONZE_RATE', '0.25', NULL),
  ('GRADE_SILVER_RATE', '0.12', NULL),
  ('GRADE_GOLD_RATE', '0.04', NULL),
  ('GRADE_DIAMOND_RATE', '0.01', NULL),
  ('GRADE_LEGENDARY_RATE', '0.001', NULL),
  ('OFFLINE_CAP_SECONDS', '57600', '16h offline cap'),
  ('PEST_SPAWN_CHANCE', '0.10', NULL),
  ('WEED_TIMER_PENALTY_MULTIPLIER', '1.25', NULL),
  ('BUG_YIELD_PENALTY', '0.50', NULL),
  ('WATER_REDUCTION_PERCENT', '0.15', NULL),
  ('MAX_WATERINGS_PER_CYCLE', '3', NULL),
  ('WITHER_YIELD_MULTIPLIER', '0.50', NULL),
  ('WITHER_TIME_MULTIPLIER', '2.0', NULL),
  ('FERTILISER_BRONZE_BOOST', '0.02', NULL),
  ('FERTILISER_SILVER_BOOST', '0.01', NULL),
  ('FRIEND_FERTILISER_BRONZE_BOOST', '0.02', NULL),
  ('FRIEND_FERTILISER_SILVER_BOOST', '0.01', NULL),
  ('MAX_FERTILISER_BRONZE_BOOST', '0.04', NULL),
  ('MAX_FERTILISER_SILVER_BOOST', '0.02', NULL),
  ('RESTAURANT_MULTIPLIER_MAX', '1.5', NULL),
  ('RESTAURANT_MULTIPLIER_BUILDUP_SECONDS', '14400', NULL),
  ('FAVOURED_DISH_BONUS', '1.30', NULL),
  ('PET_FEED_DURATION_SECONDS', '43200', NULL),
  ('PET_FOOD_COST', '10', NULL),
  ('PET_STEAL_BLOCK_CHANCE', '0.25', NULL),
  ('PET_RESTAURANT_BONUS', '0.10', NULL),
  ('PET_YIELD_BONUS', '0.10', NULL),
  ('PET_XP_BONUS', '0.15', NULL),
  ('STARTER_COINS', '500', NULL),
  ('SUNDAY_MARKET_FEE', '10000', NULL),
  ('SUNDAY_MARKET_STALL_SIZE', '5', NULL),
  ('LOTTERY_MIN_ENTRY', '100', NULL),
  ('LOTTERY_DIMINISHING_RETURNS_THRESHOLD', '10000', NULL),
  ('NOTIFICATION_BATCH_WINDOW_SECONDS', '1800', NULL)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    description = EXCLUDED.description,
    updated_at = now();

INSERT INTO game_config (key, value) VALUES
  ('crop_lettuce', '{"growTimeSeconds":3600,"seedCostCoins":5,"isPerpetual":false,"unlockLevel":1,"baseYieldMin":6,"baseYieldMax":10}'),
  ('crop_tomato', '{"growTimeSeconds":7200,"seedCostCoins":10,"isPerpetual":false,"unlockLevel":1,"baseYieldMin":5,"baseYieldMax":8}'),
  ('crop_cucumber', '{"growTimeSeconds":7200,"seedCostCoins":10,"isPerpetual":false,"unlockLevel":3,"baseYieldMin":5,"baseYieldMax":8}'),
  ('crop_onion', '{"growTimeSeconds":14400,"seedCostCoins":15,"isPerpetual":false,"unlockLevel":2,"baseYieldMin":5,"baseYieldMax":9}'),
  ('crop_wheat', '{"growTimeSeconds":14400,"seedCostCoins":15,"isPerpetual":false,"unlockLevel":1,"baseYieldMin":6,"baseYieldMax":10}'),
  ('crop_potato', '{"growTimeSeconds":21600,"seedCostCoins":20,"isPerpetual":false,"unlockLevel":4,"baseYieldMin":4,"baseYieldMax":7}'),
  ('crop_jalapeno', '{"growTimeSeconds":28800,"seedCostCoins":35,"isPerpetual":false,"unlockLevel":8,"baseYieldMin":3,"baseYieldMax":5}'),
  ('crop_sesame', '{"growTimeSeconds":43200,"seedCostCoins":45,"isPerpetual":false,"unlockLevel":12,"baseYieldMin":3,"baseYieldMax":4}'),
  ('crop_strawberry', '{"growTimeSeconds":14400,"regrowTimeSeconds":7200,"seedCostCoins":60,"isPerpetual":true,"unlockLevel":6,"baseYieldMin":10,"baseYieldMax":16}'),
  ('crop_blueberry', '{"growTimeSeconds":14400,"regrowTimeSeconds":7200,"seedCostCoins":60,"isPerpetual":true,"unlockLevel":10,"baseYieldMin":8,"baseYieldMax":12}'),
  ('crop_herb', '{"growTimeSeconds":10800,"regrowTimeSeconds":5400,"seedCostCoins":40,"isPerpetual":true,"unlockLevel":8,"baseYieldMin":6,"baseYieldMax":10}')
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    updated_at = now();
